### DISCUSSION TITLE
Config.json with Docker

### DISCUSSION THREAD

**Discussion by frantischek** [soketi/pws#1119] [Q&A]
Hello. I try to start a Docker container with `docker-compose.yml`.
I added a volume: `- ./config.json:/app/config.json` and `- SOKETI_CONFIG=/app/config.json` but thats not working. Any ideas how I can get this to run? I need the config, because I want to use webhooks.
Thanks

**Comment by davisriska** [comment]
This is what I use, might help you

```yaml
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        command: [ "node", "/app/bin/server.js", "start", "--config=/opt/config.json" ]
        volumes:
            - './docker/soketi/config.json/:/opt/config.json'
```
