### ISSUE TITLE
Network watcher Unable to subscribe to signal events

### ISSUE THREAD

**Issue by HelloChrisBrown** [soketi/pws#99]
I'm able to get the pws container up and running without issue. When I try to enable the network watcher the container is throwing the below error and never getting to a ready state.

```
Unable to subscribe to signal events. Make sure that the `pcntl` extension                                                                                                                                      
is installed and that "pcntl_*" functions are not disabled by your php.ini'                                                                                                          
  s "disable_functions" directive.
```

The deployment looks like:

```yaml
# Source: pws/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pws
  labels:
    helm.sh/chart: pws-0.2.0
    app.kubernetes.io/name: pws
    app.kubernetes.io/instance: pws
    app.kubernetes.io/version: "0.8.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pws
      app.kubernetes.io/instance: pws
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pws
        app.kubernetes.io/instance: pws
        pws.soketi.app/accepts-new-connections: "yes"
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: pws
      securityContext:
        {}

      containers:
        - name: network-watcher
          securityContext:
            {}
          image: "quay.io/soketi/network-watcher:4.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBE_CONNECTION
              value: cluster
            - name: SERVER_PORT
              value: "6001"
            - name: MEMORY_PERCENT
              value: "85"
            - name: CHECKING_INTERVAL
              value: "1"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
        - name: pws
          securityContext:
            {}
          image: "quay.io/soketi/pws:latest-16-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: pws
              containerPort: 6001
              protocol: TCP
          command:
            - node
            - --max-old-space-size=256
            - --max_old_space_size=256
            - --optimize_for_size
            - --optimize-for-size
            - --trace-warnings
            - /app/bin/server.js
            - start
          envFrom:
            - configMapRef:
                name: pws
          livenessProbe:
            httpGet:
              path: /
              port: 6001
              httpHeaders:
              - name: X-Kube-Healthcheck
                value: "Yes"
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 6001
              httpHeaders:
              - name: X-Kube-Healthcheck
                value: "Yes"
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
```
